config/routes.rb
Rails.application.routes.draw do
  resources :jv_scripts

end

app/models/jv_script.rb
class JvScript < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jv_scripts_controller.rb
class JvScriptsController < ApplicationController
  before_action :set_jv_script, only: [:show, :edit, :update, :destroy]

  # GET /jv_scripts
  # GET /jv_scripts.json
  def index
    @jv_scripts = JvScript.all
  end

  # GET /jv_scripts/1
  # GET /jv_scripts/1.json
  def show
  end

  # GET /jv_scripts/new
  def new
    @jv_script = JvScript.new
  end

  # GET /jv_scripts/1/edit
  def edit
  end

  # POST /jv_scripts
  # POST /jv_scripts.json
  def create
    @jv_script = JvScript.new(jv_script_params)

    respond_to do |format|
      if @jv_script.save
        format.html { redirect_to @jv_script, notice: 'Jv script was successfully created.' }
        format.json { render :show, status: :created, location: @jv_script }
      else
        format.html { render :new }
        format.json { render json: @jv_script.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jv_scripts/1
  # PATCH/PUT /jv_scripts/1.json
  def update
    respond_to do |format|
      if @jv_script.update(jv_script_params)
        format.html { redirect_to @jv_script, notice: 'Jv script was successfully updated.' }
        format.json { render :show, status: :ok, location: @jv_script }
      else
        format.html { render :edit }
        format.json { render json: @jv_script.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jv_scripts/1
  # DELETE /jv_scripts/1.json
  def destroy
    @jv_script.destroy
    respond_to do |format|
      format.html { redirect_to jv_scripts_url, notice: 'Jv script was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jv_script
      @jv_script = JvScript.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jv_script_params
      params.require(:jv_script).permit(:depo, :withd, :bal)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jv_scripts_helper.rb
module JvScriptsHelper
end

app/views/jv_scripts/_form.html.erb
<%= form_for(@jv_script) do |f| %>
  <% if @jv_script.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jv_script.errors.count, "error") %> prohibited this jv_script from being saved:</h2>

      <ul>
      <% @jv_script.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :depo %><br>
    <%= f.number_field :depo %>
  </div>
  <div class="field">
    <%= f.label :withd %><br>
    <%= f.number_field :withd %>
  </div>
  <div class="field">
    <%= f.label :bal %><br>
    <%= f.number_field :bal %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= javascript_tag do%>
  test();
<%end %>

app/views/jv_scripts/edit.html.erb
<h1>Editing Jv Script</h1>

<%= render 'form' %>

<%= link_to 'Show', @jv_script %> |
<%= link_to 'Back', jv_scripts_path %>

app/views/jv_scripts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Jv Scripts</h1>

<table>
  <thead>
    <tr>
      <th>Depo</th>
      <th>Withd</th>
      <th>Bal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jv_scripts.each do |jv_script| %>
      <tr>
        <td><%= jv_script.depo %></td>
        <td><%= jv_script.withd %></td>
        <td><%= jv_script.bal %></td>
        <td><%= link_to 'Show', jv_script %></td>
        <td><%= link_to 'Edit', edit_jv_script_path(jv_script) %></td>
        <td><%= link_to 'Destroy', jv_script, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jv script', new_jv_script_path %>

app/views/jv_scripts/new.html.erb
<h1>New Jv Script</h1>

<%= render 'form' %>

<%= link_to 'Back', jv_scripts_path %>

app/views/jv_scripts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Depo:</strong>
  <%= @jv_script.depo %>
</p>

<p>
  <strong>Withd:</strong>
  <%= @jv_script.withd %>
</p>

<p>
  <strong>Bal:</strong>
  <%= @jv_script.bal %>
</p>

<%= link_to 'Edit', edit_jv_script_path(@jv_script) %> |
<%= link_to 'Back', jv_scripts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JVScript</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%#= javascript_include_tag 'demo' %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>